---
- hosts: 18.138.83.147
  tasks: 
    - name: New user creation with sudo access  
      user: name =ansible
       password =  Ansible123@
       use_sudo: yes
       createhome =  yes
       state: present
       