- name: Ensure user hussain is present
  hosts: windows
  tasks:
   - name : user creation
     win_user:
        name: hussain
        password: Password1
        state: present
                groups:
          - Users
